### ISSUE TITLE
大佬还有更新的打算吗orz

### ISSUE THREAD

**Issue by kanajin** [LFTEC/LearningFucker#10]
更新之后不能用了...

**Comment by ybjy82** [comment]
周五刚更新，应该可以用了

发自我的iPhone

**Comment by kanajin** [comment]
看到更新了！抱歉
请问怎么更新呢。。小白一个抱歉

**Comment by kanajin** [comment]
> 
> 
> 看到更新了！抱歉
> 请问怎么更新呢。。小白一个抱歉

非常抱歉没有看到pre-release，无视上面这段话orz

**Comment by LFTEC** [comment]
上周发布版本有问题，修复后重新发布v1.0 @kanajin

**Comment by kanajin** [comment]
> 
> 
> 上周发布版本有问题，修复后重新发布v1.0 @kanajin

似乎答题什么的有点问题确实
看到release了！等晚上维护完我试一下！

**Comment by kanajin** [comment]
闯关答题出现个错误“无法对null执行运行时绑定”

**Comment by LFTEC** [comment]
闯关答题服务端代码一直有问题，我怀疑服务端代码有问题，经常无法返回数据
