### ISSUE TITLE
Character set utf8mb3's not supported by.Net Framework.

### ISSUE THREAD

**Issue by wu2832926282** [LFTEC/LearningFucker#18]
必修学习中出现Character set utf8mb3's not supported by.Net Framework.报错

**Comment by LFTEC** [comment]
用窗口还是命令行？

wu2832926282 ***@***.***> 于 2022年6月29日周三 21:54写道：

**Comment by wu2832926282** [comment]
窗口登录

**Comment by wu2832926282** [comment]
请问更多的密码是什么？(选修中可以正常运行，但是必修就不)

**Comment by wu2832926282** [comment]
选修可以正常进行，必修就不行

**Comment by LFTEC** [comment]
窗口登录已经不支持了，请使用cli命令行操作

**Comment by wu2832926282** [comment]
是用idea吗？请问怎么运行呢？
![image](https://user-images.githubusercontent.com/42467337/176628800-d1cf1da9-83ee-4651-b394-194eba2bb4c4.png)

**Comment by wu2832926282** [comment]
请问用什么命令呢？

**Comment by LFTEC** [comment]
请下载最新发布的v1.1版本使用，教程见首页readme帮助。

**Comment by wu2832926282** [comment]
好的，谢谢
