### ISSUE TITLE
万华学习更新后无法学习

### ISSUE THREAD

**Issue by wu2832926282** [LFTEC/LearningFucker#24]
万华学习更新后无法学习
显示lsystem32\WindowsPowerShell\v1.0\
POST Error:Api/User/Loginl "Hleaders" :[("Key" :"Content-Type" "Talue": [" application/x-ww-form-urlencoded"], f Key" Cont;nt-Length","Value": ["37"]}]}. Http Code: NotFound,Response:
user 00031237 login failed!

**Comment by LFTEC** [comment]
万华学习已更新，暂时无法线下挂分，也没法在PC浏览器上访问，请等待我们的更新。

**Comment by wu2832926282** [comment]
招代理：目前低价招代理，可低价拿卡，有单独后台，可自己开卡，现在搞活动，免费开通收代理功能
    
    代理方式：50元代理费
    
    有意者QQ联系：2832926282
    
    软件下载：教程里有下载链接
    安卓教程：
链接 
    电脑教程：
链接 
    苹果教程：
链接用户中心：链接购买：链接

**Comment by wu2832926282** [comment]
好的，感谢开发者的辛苦付出
