### ISSUE TITLE
自动学习报SSL错误

### ISSUE THREAD

**Issue by zhangbei59** [LFTEC/LearningFucker#46]
执行lf study之后，大概5秒之后报如下SSL错误，请大佬看一眼
![Uploading 038d2aea61ba9b914aec8e024175932.jpg…]()

**Comment by zhangbei59** [comment]
![038d2aea61ba9b914aec8e024175932](https://github.com/LFTEC/LearningFucker/assets/25737059/4bd3f703-4b52-4066-a2a6-2b8f359c776f)

**Comment by LFTEC** [comment]
问题已经发现，下周我找找原因

**Comment by LFTEC** [comment]
已解决
