### ISSUE TITLE
自动学习报错

### ISSUE THREAD

**Issue by zhoubei9** [LFTEC/LearningFucker#56]
执行study命令后大概30s左右  自动报  The SSL connection could not be established, see inner exception.错误。  
请大佬帮忙看一眼，另外咱这个是不是每天8点之前不能登录啊 我试过很多次进不去
感谢大佬。
![屏幕截图 2023-12-22 150601](https://github.com/LFTEC/LearningFucker/assets/150251454/11207d07-3a2a-4a7d-81b5-6e5930b2f2e1)

**Comment by LFTEC** [comment]
问题已经解决，不会报SSL错误了。
8点之前不能用确实是这样，原因我怀疑是app后台检查了前端设备，具体原因我也没分析，反正也能用

**Comment by zhoubei9** [comment]
> 问题已经解决，不会报SSL错误了。 8点之前不能用确实是这样，原因我怀疑是app后台检查了前端设备，具体原因我也没分析，反正也能用

感谢大佬！
